/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mylibrary.views;

/**
 *
 * @author HILAR
 */
public class indexForm extends javax.swing.JFrame {

    /**
     * Creates new form indexForm
     */
    public indexForm() {
        initComponents();
         setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        libroMenu = new javax.swing.JMenu();
        nuevoLibroItem = new javax.swing.JMenuItem();
        updateLibroItem = new javax.swing.JMenuItem();
        deleteLibroItem = new javax.swing.JMenuItem();
        addCopiasItem = new javax.swing.JMenuItem();
        clientesMenu = new javax.swing.JMenu();
        nuevoClienteItem = new javax.swing.JMenuItem();
        updateClienteItem = new javax.swing.JMenuItem();
        eliminarClienteItem = new javax.swing.JMenuItem();
        prestamosMenu = new javax.swing.JMenu();
        nuevoPrestamoItem = new javax.swing.JMenuItem();
        finalizarPrestamoItem = new javax.swing.JMenuItem();
        prestamosAVencerItem = new javax.swing.JMenuItem();
        autoresMenu = new javax.swing.JMenu();
        verObrasItem = new javax.swing.JMenuItem();
        nuevoAutorItem = new javax.swing.JMenuItem();
        updateAutorItem = new javax.swing.JMenuItem();
        deleteAutorItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        libroMenu.setText("Libros");

        nuevoLibroItem.setText("Añadir Libro");
        libroMenu.add(nuevoLibroItem);

        updateLibroItem.setText("Editar Libro");
        libroMenu.add(updateLibroItem);

        deleteLibroItem.setText("Eliminar Libro");
        libroMenu.add(deleteLibroItem);

        addCopiasItem.setText("Añadir Copias");
        libroMenu.add(addCopiasItem);

        menuBar.add(libroMenu);

        clientesMenu.setText("Clientes");

        nuevoClienteItem.setText("Agregar Cliente");
        clientesMenu.add(nuevoClienteItem);

        updateClienteItem.setText("Editar Cliente");
        clientesMenu.add(updateClienteItem);

        eliminarClienteItem.setText("Eliminar Cliente");
        clientesMenu.add(eliminarClienteItem);

        menuBar.add(clientesMenu);

        prestamosMenu.setText("Prestamos");

        nuevoPrestamoItem.setText("Añadir Prestamo");
        prestamosMenu.add(nuevoPrestamoItem);

        finalizarPrestamoItem.setText("Finalizar Prestamo");
        prestamosMenu.add(finalizarPrestamoItem);

        prestamosAVencerItem.setText("Prestamos A vencer");
        prestamosMenu.add(prestamosAVencerItem);

        menuBar.add(prestamosMenu);

        autoresMenu.setText("Autores");

        verObrasItem.setText("Ver Obras Por Autor");
        autoresMenu.add(verObrasItem);

        nuevoAutorItem.setText("Registrar Autor");
        autoresMenu.add(nuevoAutorItem);

        updateAutorItem.setText("Editar Autor");
        autoresMenu.add(updateAutorItem);

        deleteAutorItem.setText("Eliminar Autor");
        autoresMenu.add(deleteAutorItem);

        menuBar.add(autoresMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 632, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(indexForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(indexForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(indexForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(indexForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new indexForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem addCopiasItem;
    public javax.swing.JMenu autoresMenu;
    public javax.swing.JMenu clientesMenu;
    public javax.swing.JMenuItem deleteAutorItem;
    public javax.swing.JMenuItem deleteLibroItem;
    public javax.swing.JMenuItem eliminarClienteItem;
    public javax.swing.JMenuItem finalizarPrestamoItem;
    public javax.swing.JMenu libroMenu;
    public javax.swing.JMenuBar menuBar;
    public javax.swing.JMenuItem nuevoAutorItem;
    public javax.swing.JMenuItem nuevoClienteItem;
    public javax.swing.JMenuItem nuevoLibroItem;
    public javax.swing.JMenuItem nuevoPrestamoItem;
    public javax.swing.JMenuItem prestamosAVencerItem;
    public javax.swing.JMenu prestamosMenu;
    public javax.swing.JMenuItem updateAutorItem;
    public javax.swing.JMenuItem updateClienteItem;
    public javax.swing.JMenuItem updateLibroItem;
    public javax.swing.JMenuItem verObrasItem;
    // End of variables declaration//GEN-END:variables
}
